[package]
name = "jx-remake"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
image = "0.25.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
encoding_rs = "0.8" # Để đọc GBK
csv = "1.4" # Để đọc file tab-delimited
rand = "0.8"
minifb = "0.24"
